# Generated by Django 6.0.5 on 2026-06-02 12:05

# authentication/migrations/0001_initialize_roles.py
from django.db import migrations

def create_system_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    
    # Define our core 3 target groups
    roles = ['Operator', 'Counselor', 'Admin']
    
    for role_name in roles:
        Group.objects.get_or_create(name=role_name)

def remove_system_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    roles = ['Operator', 'Counselor', 'Admin']
    Group.objects.filter(name__in=roles).delete()

class Migration(migrations.Migration):

    dependencies = [
        # Crucial: Depends on auth system being loaded
        ('auth', '__latest__'), 
    ]

    operations = [
        migrations.RunPython(create_system_roles, reverse_code=remove_system_roles),
    ]